name: qr_sorter
description: A simple Flutter app (Android + Web) for item storage, QR generation and sorting.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core & utilities
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  uuid: ^3.0.7
  intl: ^0.17.0

  # File + sharing
  file_picker: ^5.2.10
  share_plus: ^6.3.4

  # PDF / printing / barcode / qr
  pdf: ^3.10.1
  barcode: ^2.2.3
  qr: ^3.0.2
  printing: ^5.12.2

  # UI QR widget & camera
  qr_flutter: ^4.0.0
  mobile_scanner: ^7.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true

  fonts:
    - family: MaterialIcons
      fonts:
        - asset: assets/fonts/MaterialIcons-Regular.ttf